version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: restaurante_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Aguarda o banco estar pronto
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: mysql+pymysql://user1:123@db/restaurant
    ports:
      - "8000:8000"
    command: ["./wait-for-db.sh"]
    networks:
      - restaurant-net

  frontend:
    build: ./frontend
    container_name: restaurante_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"  
    environment:
      - NEXT_PUBLIC_API_URL=http://restaurante_backend:8000
    networks:
      - restaurant-net

volumes:
  db_data:

networks:
  restaurant-net:
    driver: bridge  # Definindo a rede "restaurant-net" aqui