
services:
  db:
    image: mariadb:10.6
    container_name: restaurante_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: restaurante_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://user1:123@db/restaurant"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: restaurante_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_PUBLIC_API_BASE_URL=http://restaurante_backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
