"""Adicionando relacionamento entre orders e order_items

Revision ID: 774b3d55d965
Revises: 2cf229245738
Create Date: 2025-03-05 19:27:13.909457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774b3d55d965'
down_revision: Union[str, None] = '2cf229245738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
