"""Add closed field to orders

Revision ID: b46f2bf78c2b
Revises: 774b3d55d965
Create Date: 2025-03-06 03:13:37.017562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46f2bf78c2b'
down_revision: Union[str, None] = '774b3d55d965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('closed', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'closed_at')
    op.drop_column('orders', 'closed')
    # ### end Alembic commands ###
